// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Pijavski
SEXP Pijavski(SEXP fn, SEXP Lips, SEXP a, SEXP b, SEXP iter, SEXP prec, SEXP env);
RcppExport SEXP Pijavski_Pijavski(SEXP fnSEXP, SEXP LipsSEXP, SEXP aSEXP, SEXP bSEXP, SEXP iterSEXP, SEXP precSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
//    Rcpp::traits::input_parameter< SEXP >::type o1(o1SEXP);
//    Rcpp::traits::input_parameter< SEXP >::type o2(o2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type fn(fnSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Lips(LipsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a(aSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b(bSEXP);
    Rcpp::traits::input_parameter< SEXP >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< SEXP >::type prec(precSEXP);
    Rcpp::traits::input_parameter< SEXP >::type env(envSEXP);
    __result = Rcpp::wrap(Pijavski(fn, Lips, a, b, iter, prec, env));
    return __result;
END_RCPP
}

#include <R_ext/Rdynload.h>    
#include <R_ext/Visibility.h>

static const R_CallMethodDef callMethods[]  = {
  {NULL, NULL, 0}
};

static R_NativePrimitiveArgType myC_t[] = {
    INTSXP, REALSXP, REALSXP, REALSXP, INTSXP, REALSXP, REALSXP
};

static const R_CMethodDef cMethods[] = {
   {"Pijavski", (DL_FUNC) &Pijavski, 7, myC_t},
   {NULL, NULL, 0, NULL}
};

void
R_init_Pijavski(DllInfo *info)
{
   R_registerRoutines(info, cMethods, callMethods, NULL, NULL);
   R_useDynamicSymbols(info, TRUE); 
}
